# Generated by Django 4.0.5 on 2022-06-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Has_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Has_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('measure', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('has_ingredients', models.ManyToManyField(to='recettes.has_ingredient')),
                ('tagged', models.ManyToManyField(to='recettes.has_tags')),
            ],
        ),
        migrations.AddField(
            model_name='has_tags',
            name='kitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recipe'),
        ),
        migrations.AddField(
            model_name='has_tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.tag'),
        ),
        migrations.AddField(
            model_name='has_ingredient',
            name='ingredient',
            field=models.ManyToManyField(to='recettes.ingredient'),
        ),
        migrations.AddField(
            model_name='has_ingredient',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recipe'),
        ),
    ]
