# Generated by Django 4.0.5 on 2022-06-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tagged',
            new_name='has_label',
        ),
    ]
