# Generated by Django 4.0.5 on 2022-07-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0009_alter_ingredient_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
